-- Run this entire script in Supabase SQL Editor to update your database schema
-- It adds all the new columns matching the April Excel Sheet

ALTER TABLE employees 
  ADD COLUMN IF NOT EXISTS cnic VARCHAR(20),
  ADD COLUMN IF NOT EXISTS ntn VARCHAR(50),
  ADD COLUMN IF NOT EXISTS bank_name VARCHAR(100),
  ADD COLUMN IF NOT EXISTS iban VARCHAR(100),
  ADD COLUMN IF NOT EXISTS increment DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS new_gross_monthly DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS date_of_leaving DATE,
  -- Salary structure defaults for each employee
  ADD COLUMN IF NOT EXISTS dearness_allowance DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cola_allowance DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS utility_allowance DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS washing_allowance DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS previous_month_allowance DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS bonus_allowance DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS leave_encashment DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS overtime DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS income_tax DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS eobi_deduction DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS other_deduction DECIMAL(12, 2) DEFAULT 0;

ALTER TABLE salary_slips
  ADD COLUMN IF NOT EXISTS arrears DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS washing_allowance DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS paid_leave_amount DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS deduction_misc DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS damage_medical DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS taxable_salary DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sessi DECIMAL(12, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS note TEXT;
